In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets

import os
os.chdir("C:/Users/Kritika/Downloads/")
df = pd.read_csv("ANZ2.csv")
df

status  card_present_flag bpay_biller_code         account  \
0      authorized                1.0              NaN  ACC-1598451071   
1      authorized                0.0              NaN  ACC-1598451071   
2      authorized                1.0              NaN  ACC-1222300524   
3      authorized                1.0              NaN  ACC-1037050564   
4      authorized                1.0              NaN  ACC-1598451071   
...           ...                ...              ...             ...   
12038  authorized                0.0              NaN  ACC-3021093232   
12039  authorized                1.0              NaN  ACC-1608363396   
12040  authorized                1.0              NaN  ACC-3827517394   
12041  authorized                1.0              NaN  ACC-2920611728   
12042  authorized                1.0              NaN  ACC-1443681913   

      currency       long_lat txn_description  \
0          AUD  153.41 -27.95             POS   
1          AUD  153.41 -27.95       SALES-POS   
2          AUD  151.23 -33.94             POS   
3          AUD  153.10 -27.66       SALES-POS   
4          AUD  153.41 -27.95       SALES-POS   
...        ...            ...             ...   
12038      AUD  149.83 -29.47             POS   
12039      AUD  151.22 -33.87       SALES-POS   
12040      AUD  151.12 -33.89             POS   
12041      AUD  144.96 -37.76       SALES-POS   
12042      AUD  150.92 -33.77       SALES-POS   

                                merchant_id  merchant_code first_name  ...  \
0      81c48296-73be-44a7-befa-d053f48ce7cd            NaN      Diana  ...   
1      830a451c-316e-4a6a-bf25-e37caedca49e            NaN      Diana  ...   
2      835c231d-8cdf-4e96-859d-e9d571760cf0            NaN    Michael  ...   
3      48514682-c78a-4a88-b0da-2d6302e64673            NaN     Rhonda  ...   
4      b4e02c10-0852-4273-b8fd-7b3395e32eb0            NaN      Diana  ...   
...                                     ...            ...        ...  ...   
12038  32aa73dc-b7c2-4161-b14d-6271b96ce792            NaN    Melissa  ...   
12039  296a0500-8552-48ac-ac81-ec37065b568e            NaN     Robert  ...   
12040  e5975ab4-08f7-4725-a369-24cc0e35ed6e            NaN      Craig  ...   
12041  af49051a-591d-4b08-bd3c-27730b70ed37            NaN      Tyler  ...   
12042  f31f4b14-2040-40ec-a120-b141bb274cbd            NaN       Ryan  ...   

       age merchant_suburb merchant_state                    extraction  \
0       26         Ashmore            QLD  2018-08-01T01:01:15.000+0000   
1       26          Sydney            NSW  2018-08-01T01:13:45.000+0000   
2       38          Sydney            NSW  2018-08-01T01:26:15.000+0000   
3       40         Buderim            QLD  2018-08-01T01:38:45.000+0000   
4       26   Mermaid Beach            QLD  2018-08-01T01:51:15.000+0000   
...    ...             ...            ...                           ...   
12038   30        Ringwood            VIC  2018-10-31T23:09:06.000+0000   
12039   20          Casula            NSW  2018-10-31T23:21:46.000+0000   
12040   28      Kings Park            NSW  2018-10-31T23:34:25.000+0000   
12041   69        Oakleigh            VIC  2018-10-31T23:47:05.000+0000   
12042   31          Mascot            NSW  2018-10-31T23:59:44.000+0000   

      amount                    transaction_id    country     customer_id  \
0      16.25  a623070bfead4541a6b0fff8a09e706c  Australia  CUS-2487424745   
1      14.19  13270a2a902145da9db4c951e04b51b9  Australia  CUS-2487424745   
2       6.42  feb79e7ecd7048a5a36ec889d1a94270  Australia  CUS-2142601169   
3      40.90  2698170da3704fd981b15e64a006079e  Australia  CUS-1614226872   
4       3.25  329adf79878c4cf0aeb4188b4691c266  Australia  CUS-2487424745   
...      ...                               ...        ...             ...   
12038   9.79  f2e3e695c2ee4c50a4c8747f852cbe2e  Australia    CUS-55310383   
12039  63.87  56e147e5485f4683b9076fcaaed76640  Australia  CUS-2688605418   
12040  43.96  

In [2]:
df.columns

Index(['status', 'card_present_flag', 'bpay_biller_code', 'account',
       'currency', 'long_lat', 'txn_description', 'merchant_id',
       'merchant_code', 'first_name', 'balance', 'date', 'gender', 'age',
       'merchant_suburb', 'merchant_state', 'extraction', 'amount',
       'transaction_id', 'country', 'customer_id', 'merchant_long_lat',
       'movement'],
      dtype='object')

In [3]:
df.corr()

card_present_flag  merchant_code   balance       age  \
card_present_flag           1.000000            NaN  0.005925 -0.008405   
merchant_code                    NaN            NaN       NaN       NaN   
balance                     0.005925            NaN  1.000000  0.199329   
age                        -0.008405            NaN  0.199329  1.000000   
amount                     -0.002074            NaN  0.059178  0.029980   

                     amount  
card_present_flag -0.002074  
merchant_code           NaN  
balance            0.059178  
age                0.029980  
amount             1.000000

In [4]:
df_salaries = df[df["txn_description"]=="PAY/SALARY"].groupby("customer_id").mean()
df_salaries.head()

card_present_flag  merchant_code       balance  age   amount
customer_id                                                                 
CUS-1005756958                NaN            0.0   4718.665385   53   970.47
CUS-1117979751                NaN            0.0  11957.202857   21  3578.65
CUS-1140341822                NaN            0.0   5841.720000   28  1916.51
CUS-1147642491                NaN            0.0   8813.467692   34  1711.39
CUS-1196156254                NaN            0.0  23845.717143   34  3903.73

In [5]:
salaries = []

for customer_id in df["customer_id"]:
    salaries.append(int(df_salaries.loc[customer_id]["amount"]))
    
df["annual_salary"] = salaries

df_cus = df.groupby("customer_id").mean()
df_cus.head()

card_present_flag  merchant_code       balance  age  \
customer_id                                                           
CUS-1005756958           0.812500            0.0   2275.852055   53   
CUS-1117979751           0.826923            0.0   9829.929000   21   
CUS-1140341822           0.815385            0.0   5699.212250   28   
CUS-1147642491           0.750000            0.0   9032.841186   34   
CUS-1196156254           0.785276            0.0  22272.433755   34   

                    amount  annual_salary  
customer_id                                
CUS-1005756958  222.862603            970  
CUS-1117979751  339.843700           3578  
CUS-1140341822  212.632500           1916  
CUS-1147642491  245.600169           1711  
CUS-1196156254  147.145796           3903

## Linear Regression

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

N_train = int(len(df_cus)*0.8)
X_train = df_cus.drop("annual_salary", axis=1).iloc[:N_train]
Y_train = df_cus["annual_salary"].iloc[:N_train]
X_test = df_cus.drop("annual_salary", axis=1).iloc[N_train:]
Y_test = df_cus["annual_salary"].iloc[N_train:]

linear_reg = LinearRegression()

linear_reg.fit(X_train, Y_train)
linear_reg.score(X_train, Y_train)

0.23295376366257825

In [7]:
linear_reg.predict(X_test)

array([1993.98473311, 2867.39066481, 1944.95959591, 1806.85984885,
       2226.35045442, 2075.34697175, 1813.02987337, 5388.67435983,
       1902.35351608, 2191.90445145, 1713.48134178, 2854.40519949,
       2094.77781158, 3815.34342881, 2249.92922822, 1768.80816189,
       2095.02988288, 1515.18425875, 1782.72752537, 2481.2898546 ])

In [8]:
linear_reg.score(X_test, Y_test)

-0.3169423498074737

## Decision tree

In [9]:
df_cat = df[["txn_description", "gender", "age", "merchant_state", "movement"]]
pd.get_dummies(df_cat).head()

age  txn_description_INTER BANK  txn_description_PAY/SALARY  \
0   26                           0                           0   
1   26                           0                           0   
2   38                           0                           0   
3   40                           0                           0   
4   26                           0                           0   

   txn_description_PAYMENT  txn_description_PHONE BANK  txn_description_POS  \
0                        0                           0                    1   
1                        0                           0                    0   
2                        0                           0                    1   
3                        0                           0                    0   
4                        0                           0                    0   

   txn_description_SALES-POS  gender_F  gender_M  merchant_state_ACT  \
0                          0         1         0                   0   
1                          1         1         0                   0   
2                          0         0         1                   0   
3                          1         1         0                   0   
4                          1         1         0                   0   

   merchant_state_NSW  merchant_state_NT  merchant_state_QLD  \
0                   0                  0                   1   
1                   1                  0                   0   
2                   1                  0                   0   
3                   0                  0                   1   
4                   0                  0                   1   

   merchant_state_SA  merchant_state_TAS  merchant_state_VIC  \
0                  0                   0                   0   
1                  0                   0                   0   
2                  0                   0                   0   
3                  0                   0                   0   
4                  0                   0                   0   

   merchant_state_WA  movement_credit  movement_debit  
0                  0                0               1  
1                  0                0               1  
2                  0                0               1  
3                  0                0               1  
4                  0                0               1

In [10]:
N_train = int(len(df)*0.8)
X_train = pd.get_dummies(df_cat).iloc[:N_train]
Y_train = df["annual_salary"].iloc[:N_train]
X_test = pd.get_dummies(df_cat).iloc[N_train:]
Y_test = df["annual_salary"].iloc[N_train:]

### Classification

In [11]:
decision_tree_class = DecisionTreeClassifier()
decision_tree_class.fit(X_train, Y_train)
decision_tree_class.score(X_train, Y_train)

0.7882499481004774

In [12]:
decision_tree_class.predict(X_test)

array([1013, 1043, 4132, ..., 4054, 1043,  996], dtype=int64)

In [13]:
decision_tree_class.score(X_test, Y_test)

0.7546699875466999

### Regression

In [14]:
decision_tree_reg = DecisionTreeRegressor()

In [15]:
decision_tree_reg.fit(X_train, Y_train)
decision_tree_reg.score(X_train, Y_train)

0.7468978726536879

In [16]:
decision_tree_reg.predict(X_test)

array([1226.42857143, 1043.        , 4132.        , ..., 3345.04761905,
       1043.        , 1626.        ])

In [17]:
decision_tree_reg.score(X_test, Y_test)

0.6822815758919634